fixtures:
  forge_modules:
    dism: 'puppetlabs/dism'
    pwshlib: 'puppetlabs/pwshlib'
  fixtures:
  repositories:
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "translate": 
      "repo": "https://github.com/puppetlabs/puppetlabs-translate"
    facts: 'git://github.com/mihaibuzgau/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
  symlinks:
    "iis": "#{source_dir}"
